---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "&4Black&aPast &eFaction &6V2.1"
OutdatedClient:
  custom: true
  message: "&cVotre client MCPE est obsolète!"
OutdatedServer:
  custom: true
  message: "&cOops! Server obsolète!"
WhitelistedServer:
  custom: true
  message: "&c&oCe serveur est en liste blanche!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, Le serveur est plein &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dEssayez de vous inscrire plus tard :)"
FirstJoin:
  enable: true
  message: "&a{PLAYER}&d a rejoint le jeu pour la première fois."
Join:
  hide: true
  custom: true
  message: "&a{PLAYER}&e a rejoint le jeu."
Quit:
  hide: true
  custom: true
  message: "&c{PLAYER}&e a quitté la partie"
WorldChange:
  enable: true
  message: "&a{PLAYER}&e bouger de &c{ORIGIN}&e à &a{TARGET}"
Death:
  hide: true
  custom: true
  message: "&c{PLAYER} décédés"
  death-contact-message:
    hide: true
    custom: true
    message: "&cOops! {PLAYER} A été tué par {BLOCK}"
  kill-message:
    hide: true
    custom: true
    message: "&9{PLAYER} &eA été tué par &c{KILLER}"
  death-projectile-message:
    hide: true
    custom: true
    message: "&c{PLAYER} A été tué par {KILLER} par un ovni"
  death-suffocation-message:
    hide: true
    custom: true
    message: "&c{PLAYER} étouffé"
  death-fall-message:
    hide: true
    custom: true
    message: "&c{PLAYER} tombé d'un haut lieu"
  death-fire-message:
    hide: true
    custom: true
    message: "&c{PLAYER} est monté en flammes"
  death-on-fire-message:
    hide: true
    custom: true
    message: "&c{PLAYER} brûlé"
  death-lava-message:
    hide: true
    custom: true
    message: "&c{PLAYER} essayé de nager dans la lave"
  death-drowning-message:
    hide: true
    custom: true
    message: "&c{PLAYER} noyé"
  death-explosion-message:
    hide: true
    custom: true
    message: "&c{PLAYER} a explosé"
  death-void-message:
    hide: true
    custom: true
    message: "&c{PLAYER} est tombé dans le vide"
  death-suicide-message:
    hide: true
    custom: true
    message: "&c{PLAYER} se suicider"
  death-magic-message:
    hide: true
    custom: true
    message: "&c{PLAYER} a été tué par un sort"
...