name: BlackAlerts
main: BlackAlerts\BlackAlerts
version: 1.0.0
api: [3.2.0]
load: STARTUP
author: BlackTeam
description: Personnaliser ou masquer les alertes (messages joint / laissé, liste blanche, messages serveur / client obsolètes, etc ...) plugin

commands:
  customalerts:
    aliases: [calerts]
    description: Commandes BlackAlerts.
    permission: customalerts
permissions:
  customalerts:
    default: op
    description: Arbre d'autorisation BlackAlerts.
    children:
      customalerts.help:
        default: op
        description: laisser le joueur lire les commandes BlackAlerts aider.
      customalerts.info:
        default: op
        description: Laissez le joueur lire les informations sur BlackAlerts.
      customalerts.reload:
        default: op
        description: Laissez le lecteur recharger la configuration BlackAlerts.
