name: BlackAlerts
main: BlackAlerts\BlackAlerts
version: 2.0
api: [3.0.0-ALPHA12]
load: STARTUP
author: BlackTeam
description: Personnaliser les alertes (joindre / laisser des messages, etc ...)

commands:
  blackalerts:
    aliases: [balerts]
    description: Commandes BlackAlerts.
    permission: blackalerts
permissions:
  blackalerts:
    default: op
    description: Autorisations BlackAlerts.
    children:
      blackalerts.help:
        default: op
        description: Commande d'assistance BlackAlerts.
      blackalerts.info:
        default: op
        description: Commande BlackAlerts Autorisation Info.
      blackalerts.reload:
        default: op
        description: Commande BlackAlerts Autoriser le rechargement.