---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "&4Black&cPast &eV1.0 "
OutdatedClient:
  custom: true
  message: "&cVotre client MCPE est obsolète!"
OutdatedServer:
  custom: true
  message: "&cOops! Serveur obsolète!"
WhitelistedServer:
  custom: true
  message: "&c&oCe serveur est sur liste blanche!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, Le serveur est plein &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dVeuillez rejoindre plus tard :)"
FirstJoin:
  enable: true
  message: "&a{PLAYER}&d a rejoint notre serveur pour la premiere , souhaitons lui la bienvenue !."
Join:
  hide: false
  custom: true
  message: "&8[&a+&8] &7{PLAYER}"
Quit:
  hide: true
  custom: false
  message: "&8[&c-&8] &7{PLAYER}"
WorldChange:
  enable: false
  message: "&2[{TIME}] &a{PLAYER}&e moved from &c{ORIGIN}&e to &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "&c{PLAYER} Est mort ! Paix a son ame."
  death-contact-message:
    hide: false
    custom: true
    message: "&cOops! {PLAYER} a été tué par {BLOCK}"
  kill-message:
    hide: false
    custom: true
    message: "&9{PLAYER} &ea été pulvérisé par &c{KILLER}"
  death-projectile-message:
    hide: false
    custom: true
    message: "&c{PLAYER} &ea été sniper par {KILLER}."
  death-suffocation-message:
    hide: false
    custom: true
    message: "&c{PLAYER} c'est étoufé !"
  death-fall-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a cru qu'il pouvait voler"
  death-fire-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a été carboniser !"
  death-on-fire-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a brûlé"
  death-lava-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a essayé de nager dans la lave"
  death-drowning-message:
    hide: false
    custom: true
    message: "&c{PLAYER} c'est noyé"
  death-explosion-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a éclaté"
  death-void-message:
    hide: false
    custom: true
    message: "&c{PLAYER} A cru qu'il savait voler !"
  death-suicide-message:
    hide: false
    custom: true
    message: "&c{PLAYER} c'est suicidé"
  death-magic-message:
    hide: false
    custom: true
    message: "&c{PLAYER} a été tué par un sort"
...
